language: node_js
node_js:
- 4.1
script:
- npm test
- >-
  npm outdated --json |
  ruby -r json -e 'exit JSON
    .load(STDIN)
    .reject { |_, v| v["current"] == v["wanted"] }
    .each { |k, v| puts "#{k}: #{v["current"]} -> #{v["wanted"]}" }
    .empty?'
after_success:
- >-
  test $TRAVIS_TAG &&
  npm run psc-publish \
    | tail -n 1 \
    > output/purescript-neon-${TRAVIS_TAG}.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @output/purescript-neon-${TRAVIS_TAG}.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
