after_success:
- git status
- npm run psc-publish | tail -n 1 | gzip > output/docs.json.gz
- |
  if test $TRAVIS_TAG -a $GITHUB_TOKEN
  then
    curl -X POST http://pursuit.purescript.org/packages \
      -d @output/docs.json \
      -H 'Accept: application/json' \
      -H "Authorization: token ${GITHUB_TOKEN}" \
      -H 'Content-Encoding: gzip'
  fi
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '5'
script:
- travis_wait npm test
